//"use client";

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NabBar from "../main_components/navBar";
import MenuBar from "../main_components/menuBar";
import NavBar from "../main_components/navBar";
import { Toaster } from "@/components/ui/toaster";
import { useEffect, useState } from "react";
import { apiUrl } from "@/api_config";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fayida Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-gray-100">
      <head>
        <title>Fayida Admin Dashboard</title>
      </head>
      <body className={inter.className}>
        <Toaster />
        <div className="pb-4">
          <NavBar />
        </div>
        <div className="grid grid-cols-5   mr-5">
          <div className="col-span-1 pt-9 px-3 bg-blue-600 text-white">
            <MenuBar />
          </div>
          <div className="pt-9  px-5 col-span-4">{children} </div>
        </div>
      </body>
    </html>
  );
}
